### ISSUE TITLE
Enhancements or updates

### ISSUE THREAD

**Issue by Irbidan** [sokcuri/TweetDeckPlayer#61]
This software needs more updates because of TweetDeck enhancements or Twitter updates. There aren't new updates since 4 months ago. Greets

**Comment by Dalgona** [comment]
Thank you for your concern on this project. :heart: Due to campus schedules and other busy things, we couldn't pay attention to development of TweetDeck Player for a long time. But don't worry, this doesn't mean that we have abandoned this project. We will start working on updates again when we get some more time. In the meantime, though, please feel free to open an issue whenever you encounter a serious problem which prevents this program from working correctly.

We're leaving this issue for you to close. If you have more things to discuss with respect to this issue, feel free to write comments to this thread.

**Comment by sokcuri** [comment]
We are updated TweetDeck Player Today! Thanks for your interest. :>
